language: node_js
node_js:
  - "0.11"
  - "0.12"
before_script:
  - npm install
script:
  - npm run-script test-travis
after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2.11.2 && cat ./coverage/lcov.info | coveralls"
services:
  - mongodb
